-- Together Forge Supabase Schema
-- Run this in the Supabase SQL Editor

-- Ideas table
create table if not exists ideas (
	id bigint generated by default as identity primary key,
	title text not null,
	summary text,
	description text,
	category text,
	votes integer default 0,
	last_vote_time timestamptz,
	created_at timestamptz default now(),
	user_id uuid references auth.users(id)
);

-- Ensure user_id exists for idea ownership (idempotent)
alter table if exists ideas add column if not exists user_id uuid references auth.users(id);

-- New columns for the enhanced submission form (idempotent)
alter table if exists ideas add column if not exists problem_statement text;
alter table if exists ideas add column if not exists tags text;
alter table if exists ideas add column if not exists twitch_integration text;
alter table if exists ideas add column if not exists inspiration text;
alter table if exists ideas add column if not exists multiplayer_type text;
alter table if exists ideas add column if not exists visual_style text;
alter table if exists ideas add column if not exists game_setting text;
alter table if exists ideas add column if not exists environmental_storytelling text;
alter table if exists ideas add column if not exists ai_enemies boolean default false;
alter table if exists ideas add column if not exists adaptive_ai boolean default false;
alter table if exists ideas add column if not exists progression_system text;
alter table if exists ideas add column if not exists economy_description text;
alter table if exists ideas add column if not exists story_overview text;
alter table if exists ideas add column if not exists endgame_potential text;
alter table if exists ideas add column if not exists additional_notes text;

-- Votes table (for tracking individual votes with timestamps for decay)
create table if not exists votes (
	id bigint generated by default as identity primary key,
	idea_id bigint references ideas(id) on delete cascade,
	user_id uuid references auth.users(id),
	created_at timestamptz default now()
);

-- Comments table (threaded discussions)
create table if not exists comments (
	id bigint generated by default as identity primary key,
	idea_id bigint references ideas(id) on delete cascade,
	user_id uuid references auth.users(id),
	content text not null,
	created_at timestamptz default now()
);

-- Donations table
create table if not exists donations (
	id bigint generated by default as identity primary key,
	amount integer not null,
	tier_label text,
	user_id uuid references auth.users(id),
	created_at timestamptz default now()
);

-- Profiles table (extends auth.users)
create table if not exists profiles (
	id uuid references auth.users(id) primary key,
	username text unique,
	email text,
	avatar_url text,
	bio text,
	interests text,
	favorite_games text,
	favorite_game_types text,
	joined_at timestamptz default now()
);

-- Add new profile fields when migrating an existing DB (safe, idempotent)
alter table if exists profiles add column if not exists bio text;
alter table if exists profiles add column if not exists interests text;
alter table if exists profiles add column if not exists favorite_games text;
alter table if exists profiles add column if not exists favorite_game_types text;
alter table if exists profiles add column if not exists discord text;
alter table if exists profiles add column if not exists youtube text;
alter table if exists profiles add column if not exists twitch text;
alter table if exists profiles add column if not exists x_handle text;
alter table if exists profiles add column if not exists signature text;

-- Case-insensitive unique index for usernames
create unique index if not exists idx_profiles_username_lower on profiles (lower(username));

/*
  === SUPABASE STORAGE SETUP (Manual) ===
  1. Go to Storage in Supabase Dashboard
  2. Create a new bucket called: avatars (make it Public)
  3. Run the following policies in SQL Editor:

  -- Allow authenticated users to upload avatars to their own folder
  create policy "Users can upload own avatar"
  on storage.objects for insert
  with check (
    bucket_id = 'avatars' 
    and auth.uid()::text = (storage.foldername(name))[1]
  );

  -- Allow users to update their own avatar
  create policy "Users can update own avatar"
  on storage.objects for update
  using (
    bucket_id = 'avatars' 
    and auth.uid()::text = (storage.foldername(name))[1]
  );

  -- Allow public read access to avatars
  create policy "Public can read avatars"
  on storage.objects for select
  using (bucket_id = 'avatars');
*/

/* === RLS POLICIES FOR PROFILES (required for reliable profile persistence) === */

-- Allow users to read their own profile
drop policy if exists "Users can read own profile" on profiles;
create policy "Users can read own profile"
on profiles for select
using (auth.uid() = id);

-- Allow users to update their own profile
drop policy if exists "Users can update own profile" on profiles;
create policy "Users can update own profile"
on profiles for update
using (auth.uid() = id)
with check (auth.uid() = id);

-- Allow authenticated users to insert their own profile row (critical for signup)
drop policy if exists "Users can insert own profile" on profiles;
create policy "Users can insert own profile"
on profiles for insert
with check (auth.uid() = id);

-- Allow public read of usernames only (for comments display)
drop policy if exists "Public can read usernames" on profiles;
create policy "Public can read usernames"
on profiles for select
using (true);

-- Enable Row Level Security (RLS)
alter table ideas enable row level security;
alter table votes enable row level security;
alter table comments enable row level security;
alter table donations enable row level security;
alter table profiles enable row level security;

-- Basic public read policies (idempotent)
drop policy if exists "Public can read ideas" on ideas;
create policy "Public can read ideas" on ideas for select using (true);

drop policy if exists "Public can read comments" on comments;
create policy "Public can read comments" on comments for select using (true);

-- Allow anyone to submit ideas (public insert) — replace later with auth-only
drop policy if exists "Anyone can submit ideas" on ideas;
create policy "Anyone can submit ideas" on ideas for insert with check (true);

-- Owners can delete their own ideas
drop policy if exists "Owners can delete own ideas" on ideas;
create policy "Owners can delete own ideas" on ideas for delete using (auth.uid() = user_id);

-- Later, when using auth, replace the above with:
-- drop policy if exists "Anyone can submit ideas" on ideas;
-- create policy "Authenticated users can insert ideas" on ideas for insert with check (auth.uid() is not null);

-- Authenticated users can insert their own data (idempotent)
drop policy if exists "Authenticated users can insert votes" on votes;
create policy "Authenticated users can insert votes" on votes for insert with check (auth.uid() = user_id);

drop policy if exists "Authenticated users can insert comments" on comments;
create policy "Authenticated users can insert comments" on comments for insert with check (auth.uid() = user_id);

drop policy if exists "Authenticated users can insert donations" on donations;
create policy "Authenticated users can insert donations" on donations for insert with check (auth.uid() = user_id);

-- Recommended: unique constraint to prevent duplicate votes (run separately if needed)
-- create unique index if not exists idx_votes_idea_user on votes(idea_id, user_id);
-- Then replace the insert policy with stricter RLS that also enforces uniqueness via DB.

-- Username history table (for rate limiting + squatting prevention)
create table if not exists username_history (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade,
    old_username text not null,
    changed_at timestamptz default now()
);

alter table username_history enable row level security;

-- Users can read their own history
drop policy if exists "Users can read own username history" on username_history;
create policy "Users can read own username history" on username_history
for select using (auth.uid() = user_id);

-- Users can insert their own history records
drop policy if exists "Users can insert own username history" on username_history;
create policy "Users can insert own username history" on username_history
for insert with check (auth.uid() = user_id);
