-- Together Forge Supabase Schema
-- Run this in the Supabase SQL Editor

-- Ideas table
create table if not exists ideas (
	id bigint generated by default as identity primary key,
	title text not null,
	summary text,
	description text,
	category text,
	votes integer default 0,
	last_vote_time timestamptz,
	created_at timestamptz default now()
);

-- Votes table (for tracking individual votes with timestamps for decay)
create table if not exists votes (
	id bigint generated by default as identity primary key,
	idea_id bigint references ideas(id) on delete cascade,
	user_id uuid references auth.users(id),
	created_at timestamptz default now()
);

-- Comments table (threaded discussions)
create table if not exists comments (
	id bigint generated by default as identity primary key,
	idea_id bigint references ideas(id) on delete cascade,
	user_id uuid references auth.users(id),
	content text not null,
	created_at timestamptz default now()
);

-- Donations table
create table if not exists donations (
	id bigint generated by default as identity primary key,
	amount integer not null,
	tier_label text,
	user_id uuid references auth.users(id),
	created_at timestamptz default now()
);

-- Profiles table (extends auth.users)
create table if not exists profiles (
	id uuid references auth.users(id) primary key,
	username text,
	email text,
	joined_at timestamptz default now()
);

-- Enable Row Level Security (RLS)
alter table ideas enable row level security;
alter table votes enable row level security;
alter table comments enable row level security;
alter table donations enable row level security;
alter table profiles enable row level security;

-- Basic public read policies (idempotent)
drop policy if exists "Public can read ideas" on ideas;
create policy "Public can read ideas" on ideas for select using (true);

drop policy if exists "Public can read comments" on comments;
create policy "Public can read comments" on comments for select using (true);

-- Allow anyone to submit ideas (public insert) — replace later with auth-only
drop policy if exists "Anyone can submit ideas" on ideas;
create policy "Anyone can submit ideas" on ideas for insert with check (true);

-- Later, when using auth, replace the above with:
-- drop policy if exists "Anyone can submit ideas" on ideas;
-- create policy "Authenticated users can insert ideas" on ideas for insert with check (auth.uid() is not null);

-- Authenticated users can insert their own data (idempotent)
drop policy if exists "Authenticated users can insert votes" on votes;
create policy "Authenticated users can insert votes" on votes for insert with check (auth.uid() = user_id);

drop policy if exists "Authenticated users can insert comments" on comments;
create policy "Authenticated users can insert comments" on comments for insert with check (auth.uid() = user_id);

drop policy if exists "Authenticated users can insert donations" on donations;
create policy "Authenticated users can insert donations" on donations for insert with check (auth.uid() = user_id);

-- Recommended: unique constraint to prevent duplicate votes (run separately if needed)
-- create unique index if not exists idx_votes_idea_user on votes(idea_id, user_id);
-- Then replace the insert policy with stricter RLS that also enforces uniqueness via DB.
