-- Together Forge: votes table policies + unique constraint
-- Run this in the Supabase SQL Editor so like/unlike works end-to-end.
-- Idempotent.

-- ---------------------------------------------------------------------------
-- Table + uniqueness
-- ---------------------------------------------------------------------------
create table if not exists votes (
  id bigint generated by default as identity primary key,
  idea_id bigint not null references ideas(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz default now()
);

-- One vote per user per idea
create unique index if not exists idx_votes_idea_user on votes (idea_id, user_id);

create index if not exists idx_votes_user_id on votes (user_id);
create index if not exists idx_votes_idea_id on votes (idea_id);

-- ---------------------------------------------------------------------------
-- RLS: without SELECT users cannot see their votes after refresh;
-- without DELETE users cannot unvote.
-- ---------------------------------------------------------------------------
alter table votes enable row level security;

drop policy if exists "Public can read votes" on votes;
create policy "Public can read votes"
  on votes for select
  using (true);

drop policy if exists "Authenticated users can insert votes" on votes;
create policy "Authenticated users can insert votes"
  on votes for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own votes" on votes;
create policy "Users can delete own votes"
  on votes for delete
  using (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- Keep ideas.votes in sync via trigger (authoritative path)
-- ---------------------------------------------------------------------------
create or replace function public.refresh_idea_vote_count()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_idea bigint;
  new_count integer;
begin
  target_idea := coalesce(new.idea_id, old.idea_id);
  select count(*)::integer into new_count from votes where idea_id = target_idea;
  update ideas
    set votes = new_count,
        last_vote_time = case when new_count > 0 then now() else last_vote_time end
  where id = target_idea;
  return coalesce(new, old);
exception
  when undefined_column then
    -- last_vote_time may not exist on older DBs
    update ideas set votes = new_count where id = target_idea;
    return coalesce(new, old);
end;
$$;

drop trigger if exists trg_votes_refresh_count on votes;
create trigger trg_votes_refresh_count
  after insert or delete on votes
  for each row
  execute function public.refresh_idea_vote_count();

-- One-time backfill of denormalized counts
update ideas i
set votes = coalesce((
  select count(*)::integer from votes v where v.idea_id = i.id
), 0);

comment on table votes is 'Per-user idea votes. UI reads rows for liked state; count(*) and ideas.votes for totals.';
