-- Together Forge: donations table for Stripe Support + public aggregates
-- Run in Supabase SQL Editor after base schema. Safe to re-run.
--
-- Webhook (service role) inserts rows. Clients never write completed payments.
-- Public can only read anonymized aggregates via get_public_support_summary().

-- ---------------------------------------------------------------------------
-- Table + columns
-- ---------------------------------------------------------------------------
create table if not exists donations (
  id bigint generated by default as identity primary key,
  amount integer, -- legacy: whole dollars (optional)
  tier_label text,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz default now()
);

alter table donations add column if not exists amount_cents integer;
alter table donations add column if not exists currency text default 'usd';
alter table donations add column if not exists interval text default 'once';
  -- once | month
alter table donations add column if not exists fund_type text default 'studio';
  -- studio | runway
alter table donations add column if not exists tier_id text;
alter table donations add column if not exists status text default 'completed';
  -- completed | refunded | failed
alter table donations add column if not exists is_anonymous boolean default true;
alter table donations add column if not exists stripe_session_id text;
alter table donations add column if not exists stripe_payment_intent text;
alter table donations add column if not exists stripe_subscription_id text;
alter table donations add column if not exists stripe_customer_id text;
alter table donations add column if not exists raw_event_id text;

-- Prefer amount_cents; backfill from amount if present
update donations
set amount_cents = amount * 100
where amount_cents is null and amount is not null;

create unique index if not exists idx_donations_stripe_session
  on donations (stripe_session_id)
  where stripe_session_id is not null;

create unique index if not exists idx_donations_stripe_payment_intent
  on donations (stripe_payment_intent)
  where stripe_payment_intent is not null;

create index if not exists idx_donations_fund_created
  on donations (fund_type, created_at desc);

create index if not exists idx_donations_status
  on donations (status);

alter table donations enable row level security;

-- No public select of raw rows (PII / stripe ids). Service role bypasses RLS.
drop policy if exists "Authenticated users can insert donations" on donations;
drop policy if exists "Public can read donations" on donations;
drop policy if exists "Users can read own donations" on donations;

-- Users may read only their own rows (account history later)
create policy "Users can read own donations"
  on donations for select
  to authenticated
  using (auth.uid() = user_id);

-- No client inserts of "completed" payments. Webhook uses service role.
-- Optional: allow authenticated to insert draft/pending if needed later (not enabled).

-- ---------------------------------------------------------------------------
-- Public aggregate RPC (anonymized)
-- ---------------------------------------------------------------------------
create or replace function get_public_support_summary()
returns json
language sql
stable
security definer
set search_path = public
as $$
  select json_build_object(
    'studio_total_cents', coalesce(sum(amount_cents) filter (
      where coalesce(fund_type, 'studio') = 'studio'
        and coalesce(status, 'completed') in ('completed', 'paid', 'succeeded')
    ), 0),
    'studio_payment_count', coalesce(count(*) filter (
      where coalesce(fund_type, 'studio') = 'studio'
        and coalesce(status, 'completed') in ('completed', 'paid', 'succeeded')
    ), 0),
    'runway_total_cents', coalesce(sum(amount_cents) filter (
      where fund_type = 'runway'
        and coalesce(status, 'completed') in ('completed', 'paid', 'succeeded')
    ), 0),
    'runway_payment_count', coalesce(count(*) filter (
      where fund_type = 'runway'
        and coalesce(status, 'completed') in ('completed', 'paid', 'succeeded')
    ), 0),
    'last_payment_at', max(created_at) filter (
      where coalesce(status, 'completed') in ('completed', 'paid', 'succeeded')
    ),
    'currency', 'usd'
  )
  from donations;
$$;

grant execute on function get_public_support_summary() to anon, authenticated;

comment on table donations is
  'Stripe-backed support records. Written by webhook (service role). Public totals via get_public_support_summary().';
comment on function get_public_support_summary is
  'Anonymized studio + runway support totals for Transparency Hub.';
