-- =============================================================================
-- Together Forge — CORE schema (run FIRST on any new project / staging)
-- Safe to re-run. Creates public.ideas, profiles, votes, comments, donations.
-- =============================================================================

create schema if not exists public;
set search_path to public;

-- ---------------------------------------------------------------------------
-- Ideas
-- ---------------------------------------------------------------------------
create table if not exists public.ideas (
  id bigint generated by default as identity primary key,
  title text not null,
  summary text,
  description text,
  category text,
  votes integer default 0,
  last_vote_time timestamptz,
  created_at timestamptz default now(),
  user_id uuid references auth.users (id)
);

alter table public.ideas add column if not exists user_id uuid references auth.users (id);
alter table public.ideas add column if not exists problem_statement text;
alter table public.ideas add column if not exists tags text;
alter table public.ideas add column if not exists twitch_integration text;
alter table public.ideas add column if not exists inspiration text;
alter table public.ideas add column if not exists multiplayer_type text;
alter table public.ideas add column if not exists visual_style text;
alter table public.ideas add column if not exists game_setting text;
alter table public.ideas add column if not exists environmental_storytelling text;
alter table public.ideas add column if not exists ai_enemies boolean default false;
alter table public.ideas add column if not exists adaptive_ai boolean default false;
alter table public.ideas add column if not exists progression_system text;
alter table public.ideas add column if not exists economy_description text;
alter table public.ideas add column if not exists story_overview text;
alter table public.ideas add column if not exists endgame_potential text;
alter table public.ideas add column if not exists additional_notes text;
alter table public.ideas add column if not exists project_id text;

create index if not exists idx_ideas_project_id on public.ideas (project_id);

-- ---------------------------------------------------------------------------
-- Votes
-- ---------------------------------------------------------------------------
create table if not exists public.votes (
  id bigint generated by default as identity primary key,
  idea_id bigint references public.ideas (id) on delete cascade,
  user_id uuid references auth.users (id),
  created_at timestamptz default now()
);

-- ---------------------------------------------------------------------------
-- Comments
-- ---------------------------------------------------------------------------
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  idea_id bigint references public.ideas (id) on delete cascade,
  user_id uuid references auth.users (id),
  content text not null,
  created_at timestamptz default now()
);

-- ---------------------------------------------------------------------------
-- Donations (shell; Stripe columns added by supabase_donations_stripe.sql)
-- ---------------------------------------------------------------------------
create table if not exists public.donations (
  id bigint generated by default as identity primary key,
  amount integer,
  tier_label text,
  user_id uuid references auth.users (id),
  created_at timestamptz default now()
);

-- ---------------------------------------------------------------------------
-- Profiles (extends auth.users)
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
  id uuid references auth.users (id) primary key,
  username text unique,
  email text,
  avatar_url text,
  bio text,
  interests text,
  favorite_games text,
  favorite_game_types text,
  joined_at timestamptz default now()
);

alter table public.profiles add column if not exists bio text;
alter table public.profiles add column if not exists interests text;
alter table public.profiles add column if not exists favorite_games text;
alter table public.profiles add column if not exists favorite_game_types text;
alter table public.profiles add column if not exists banner_url text;
alter table public.profiles add column if not exists banner_position text default '50% 50%';
alter table public.profiles add column if not exists discord text;
alter table public.profiles add column if not exists youtube text;
alter table public.profiles add column if not exists twitch text;
alter table public.profiles add column if not exists x_handle text;
alter table public.profiles add column if not exists signature text;
alter table public.profiles add column if not exists role text default 'user';

create unique index if not exists idx_profiles_username_lower
  on public.profiles (lower(username));

-- ---------------------------------------------------------------------------
-- Username history
-- ---------------------------------------------------------------------------
create table if not exists public.username_history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete cascade,
  old_username text not null,
  changed_at timestamptz default now()
);

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
alter table public.ideas enable row level security;
alter table public.votes enable row level security;
alter table public.comments enable row level security;
alter table public.donations enable row level security;
alter table public.profiles enable row level security;
alter table public.username_history enable row level security;

-- Profiles
drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile"
  on public.profiles for select
  using (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile"
  on public.profiles for insert
  with check (auth.uid() = id);

drop policy if exists "Public can read usernames" on public.profiles;
create policy "Public can read usernames"
  on public.profiles for select
  using (true);

-- Ideas
drop policy if exists "Public can read ideas" on public.ideas;
create policy "Public can read ideas"
  on public.ideas for select
  using (true);

drop policy if exists "Anyone can submit ideas" on public.ideas;
drop policy if exists "Authenticated users can insert ideas" on public.ideas;
create policy "Authenticated users can insert ideas"
  on public.ideas for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Owners can delete own ideas" on public.ideas;
create policy "Owners can delete own ideas"
  on public.ideas for delete
  using (auth.uid() = user_id);

-- Comments
drop policy if exists "Public can read comments" on public.comments;
create policy "Public can read comments"
  on public.comments for select
  using (true);

drop policy if exists "Authenticated users can insert comments" on public.comments;
create policy "Authenticated users can insert comments"
  on public.comments for insert
  with check (auth.uid() = user_id);

-- Votes
drop policy if exists "Authenticated users can insert votes" on public.votes;
create policy "Authenticated users can insert votes"
  on public.votes for insert
  with check (auth.uid() = user_id);

-- Donations (client insert usually disabled later by Stripe-only flow)
drop policy if exists "Authenticated users can insert donations" on public.donations;
create policy "Authenticated users can insert donations"
  on public.donations for insert
  with check (auth.uid() = user_id);

-- Username history
drop policy if exists "Users can read own username history" on public.username_history;
create policy "Users can read own username history"
  on public.username_history for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own username history" on public.username_history;
create policy "Users can insert own username history"
  on public.username_history for insert
  with check (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- VERIFY (must return non-null for both)
-- ---------------------------------------------------------------------------
-- select to_regclass('public.ideas'), to_regclass('public.profiles');

-- PostgREST roles need explicit grants on greenfield projects
grant usage on schema public to anon, authenticated, service_role;
grant select on table public.profiles to anon, authenticated, service_role;
grant insert, update on table public.profiles to authenticated, service_role;
grant select, insert on table public.username_history to authenticated, service_role;
grant select on table public.ideas to anon, authenticated, service_role;
grant insert, update, delete on table public.ideas to authenticated, service_role;
grant select on table public.votes to anon, authenticated, service_role;
grant insert, delete on table public.votes to authenticated, service_role;
grant select on table public.comments to anon, authenticated, service_role;
grant insert, update, delete on table public.comments to authenticated, service_role;
grant usage, select on all sequences in schema public to authenticated, service_role;

notify pgrst, 'reload schema';
