-- Together Forge — Ideas guided wizard + workflow status
-- Run this in the Supabase SQL Editor (idempotent).
-- Do NOT auto-run from the app.

-- Workflow status: Proposed | UnderReview | Adopted | Archived
alter table if exists ideas
  add column if not exists status text default 'Proposed';

-- Structured guided-wizard fields (mechanics, gameplay intent, features, etc.)
alter table if exists ideas
  add column if not exists guided_data jsonb default '{}'::jsonb;

-- Optional: store features as JSON (legacy form / wizard step 2)
alter table if exists ideas
  add column if not exists features jsonb;

-- Link ideas to project workspaces (slug or uuid text)
alter table if exists ideas
  add column if not exists project_id text;

create index if not exists idx_ideas_status on ideas (status);
create index if not exists idx_ideas_project_id on ideas (project_id);
create index if not exists idx_ideas_guided_data on ideas using gin (guided_data);

-- Threaded comments
alter table if exists comments
  add column if not exists parent_id bigint references comments(id) on delete cascade;

create index if not exists idx_comments_parent_id on comments (parent_id);

-- Comment likes (for threaded discussion voting)
create table if not exists comment_likes (
  id bigint generated by default as identity primary key,
  comment_id bigint not null references comments(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz default now(),
  unique (comment_id, user_id)
);

alter table comment_likes enable row level security;

drop policy if exists "Public can read comment_likes" on comment_likes;
create policy "Public can read comment_likes"
  on comment_likes for select using (true);

drop policy if exists "Users manage own comment likes" on comment_likes;
create policy "Users manage own comment likes"
  on comment_likes for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Owners can update their own ideas (edit / soft-archive later)
drop policy if exists "Owners can update own ideas" on ideas;
create policy "Owners can update own ideas"
  on ideas for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

comment on column ideas.status is 'Workflow: Proposed | UnderReview | Adopted | Archived';
comment on column ideas.guided_data is 'JSON from Guided Idea Creation wizard (step 2 structured fields)';
