-- Public social proof for Support page (totals + anonymized recent feed)
-- Run after supabase/sql/supabase_donations_stripe.sql. Safe to re-run.
--
-- Adds:
--   - get_public_support_summary()  → includes MRR + all-time totals
--   - get_public_recent_donations(n, fund) → last N payments for studio or runway
-- Names/avatars only when is_anonymous = false. Emails and Stripe IDs stay off the wire.

-- Ensure columns exist (idempotent)
create table if not exists donations (
  id bigint generated by default as identity primary key,
  amount integer,
  tier_label text,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz default now()
);

alter table donations add column if not exists amount_cents integer;
alter table donations add column if not exists currency text default 'usd';
alter table donations add column if not exists interval text default 'once';
alter table donations add column if not exists fund_type text default 'studio';
alter table donations add column if not exists status text default 'completed';
alter table donations add column if not exists is_anonymous boolean default true;
alter table donations add column if not exists stripe_subscription_id text;
-- Guest / checkout credit label (also added by donation_project_attribution)
alter table donations add column if not exists display_name text;

-- ---------------------------------------------------------------------------
-- Summary: all-time studio raised + estimated MRR (active monthly subs)
-- ---------------------------------------------------------------------------
create or replace function get_public_support_summary()
returns json
language sql
stable
security definer
set search_path = public
as $$
  with completed as (
    select *
    from donations
    where coalesce(status, 'completed') in ('completed', 'paid', 'succeeded')
  ),
  studio as (
    select *
    from completed
    where coalesce(fund_type, 'studio') = 'studio'
  ),
  -- Latest payment amount per subscription id (proxy for active MRR)
  latest_sub as (
    select distinct on (stripe_subscription_id)
      stripe_subscription_id,
      amount_cents
    from studio
    where interval = 'month'
      and stripe_subscription_id is not null
      and coalesce(amount_cents, 0) > 0
    order by stripe_subscription_id, created_at desc
  )
  select json_build_object(
    'studio_total_cents', coalesce((select sum(amount_cents) from studio), 0),
    'studio_payment_count', coalesce((select count(*) from studio), 0),
    'studio_mrr_cents', coalesce((select sum(amount_cents) from latest_sub), 0),
    'studio_subscriber_count', coalesce((select count(*) from latest_sub), 0),
    'runway_total_cents', coalesce((
      select sum(amount_cents) from completed where fund_type = 'runway'
    ), 0),
    'runway_payment_count', coalesce((
      select count(*) from completed where fund_type = 'runway'
    ), 0),
    'last_payment_at', (select max(created_at) from studio),
    'currency', 'usd'
  );
$$;

grant execute on function get_public_support_summary() to anon, authenticated;

-- ---------------------------------------------------------------------------
-- Recent donations (studio or runway). Names only when not anonymous.
-- ---------------------------------------------------------------------------
drop function if exists public.get_public_recent_donations(integer);

create or replace function get_public_recent_donations(
  limit_n integer default 12,
  p_fund_type text default 'studio'
)
returns json
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (
      select json_agg(row_to_json(t))
      from (
        select
          coalesce(d.amount_cents, d.amount * 100, 0)::integer as amount_cents,
          d.created_at,
          (coalesce(d.interval, 'once') = 'month') as is_recurring,
          coalesce(d.is_anonymous, true) as is_anonymous,
          case
            when coalesce(d.is_anonymous, true) = false then p.username
            else null
          end as username,
          case
            when coalesce(d.is_anonymous, true) = false then p.avatar_url
            else null
          end as avatar_url,
          case
            when coalesce(d.is_anonymous, true) = false then
              coalesce(
                nullif(trim(p.username), ''),
                nullif(trim(d.display_name), ''),
                null
              )
            else null
          end as display_name
        from donations d
        left join profiles p on p.id = d.user_id
        where coalesce(d.fund_type, 'studio') = coalesce(nullif(trim(p_fund_type), ''), 'studio')
          and coalesce(d.status, 'completed') in ('completed', 'paid', 'succeeded')
          and coalesce(d.amount_cents, d.amount * 100, 0) > 0
        order by d.created_at desc nulls last
        limit least(greatest(coalesce(limit_n, 12), 1), 20)
      ) t
    ),
    '[]'::json
  );
$$;

grant execute on function get_public_recent_donations(integer, text)
  to anon, authenticated;

comment on function get_public_support_summary is
  'Anonymized studio totals + MRR for Support and Transparency pages.';
comment on function get_public_recent_donations(integer, text) is
  'Last N completed payments for studio or runway. Username/avatar only when not anonymous.';

-- ---------------------------------------------------------------------------
-- Unique public supporters for one fund (studio or runway). No anonymous rows.
-- ---------------------------------------------------------------------------
create or replace function get_public_fund_contributors(
  p_fund_type text default 'studio'
)
returns json
language sql
stable
security definer
set search_path = public
as $$
  with named as (
    select
      d.user_id,
      coalesce(
        nullif(trim(p.username), ''),
        nullif(trim(d.display_name), '')
      ) as display_name,
      nullif(trim(p.username), '') as username,
      p.avatar_url,
      d.created_at,
      coalesce(
        case when d.user_id is not null then 'u:' || d.user_id::text end,
        'n:' || lower(trim(coalesce(
          nullif(trim(p.username), ''),
          nullif(trim(d.display_name), ''),
          ''
        )))
      ) as person_key
    from public.donations d
    left join public.profiles p on p.id = d.user_id
    where coalesce(d.fund_type, 'studio') =
      coalesce(nullif(trim(p_fund_type), ''), 'studio')
      and coalesce(d.status, 'completed') in ('completed', 'paid', 'succeeded')
      and coalesce(d.amount_cents, d.amount * 100, 0) > 0
      and coalesce(d.is_anonymous, true) = false
  ),
  keyed as (
    select *
    from named
    where display_name is not null
      and person_key is not null
      and person_key <> 'n:'
  ),
  first_seen as (
    select distinct on (person_key)
      person_key,
      display_name,
      username,
      avatar_url,
      created_at as first_at
    from keyed
    order by person_key, created_at asc nulls last
  )
  select coalesce(
    (
      select json_agg(row_to_json(t))
      from (
        select
          display_name,
          username,
          avatar_url,
          first_at
        from first_seen
        order by lower(display_name)
      ) t
    ),
    '[]'::json
  );
$$;

grant execute on function get_public_fund_contributors(text)
  to anon, authenticated;

comment on function get_public_fund_contributors(text) is
  'Unique opted-in supporters for studio or runway. No anonymous rows, no duplicates.';

notify pgrst, 'reload schema';
