-- Public social proof for Support page (totals + anonymized recent feed)
-- Run after supabase/sql/supabase_donations_stripe.sql. Safe to re-run.
--
-- Adds:
--   - get_public_support_summary()  → includes MRR + all-time totals
--   - get_public_recent_donations(n) → last N anonymized studio payments
-- No names, emails, or Stripe IDs are returned to the client.

-- Ensure columns exist (idempotent)
create table if not exists donations (
  id bigint generated by default as identity primary key,
  amount integer,
  tier_label text,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz default now()
);

alter table donations add column if not exists amount_cents integer;
alter table donations add column if not exists currency text default 'usd';
alter table donations add column if not exists interval text default 'once';
alter table donations add column if not exists fund_type text default 'studio';
alter table donations add column if not exists status text default 'completed';
alter table donations add column if not exists is_anonymous boolean default true;
alter table donations add column if not exists stripe_subscription_id text;

-- ---------------------------------------------------------------------------
-- Summary: all-time studio raised + estimated MRR (active monthly subs)
-- ---------------------------------------------------------------------------
create or replace function get_public_support_summary()
returns json
language sql
stable
security definer
set search_path = public
as $$
  with completed as (
    select *
    from donations
    where coalesce(status, 'completed') in ('completed', 'paid', 'succeeded')
  ),
  studio as (
    select *
    from completed
    where coalesce(fund_type, 'studio') = 'studio'
  ),
  -- Latest payment amount per subscription id (proxy for active MRR)
  latest_sub as (
    select distinct on (stripe_subscription_id)
      stripe_subscription_id,
      amount_cents
    from studio
    where interval = 'month'
      and stripe_subscription_id is not null
      and coalesce(amount_cents, 0) > 0
    order by stripe_subscription_id, created_at desc
  )
  select json_build_object(
    'studio_total_cents', coalesce((select sum(amount_cents) from studio), 0),
    'studio_payment_count', coalesce((select count(*) from studio), 0),
    'studio_mrr_cents', coalesce((select sum(amount_cents) from latest_sub), 0),
    'studio_subscriber_count', coalesce((select count(*) from latest_sub), 0),
    'runway_total_cents', coalesce((
      select sum(amount_cents) from completed where fund_type = 'runway'
    ), 0),
    'runway_payment_count', coalesce((
      select count(*) from completed where fund_type = 'runway'
    ), 0),
    'last_payment_at', (select max(created_at) from studio),
    'currency', 'usd'
  );
$$;

grant execute on function get_public_support_summary() to anon, authenticated;

-- ---------------------------------------------------------------------------
-- Recent donations (anonymized feed for Support page)
-- ---------------------------------------------------------------------------
create or replace function get_public_recent_donations(limit_n integer default 12)
returns json
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (
      select json_agg(row_to_json(t))
      from (
        select
          coalesce(amount_cents, amount * 100, 0)::integer as amount_cents,
          created_at,
          (coalesce(interval, 'once') = 'month') as is_recurring,
          true as is_anonymous
        from donations
        where coalesce(fund_type, 'studio') = 'studio'
          and coalesce(status, 'completed') in ('completed', 'paid', 'succeeded')
          and coalesce(amount_cents, amount * 100, 0) > 0
        order by created_at desc nulls last
        limit least(greatest(coalesce(limit_n, 12), 1), 20)
      ) t
    ),
    '[]'::json
  );
$$;

grant execute on function get_public_recent_donations(integer) to anon, authenticated;

comment on function get_public_support_summary is
  'Anonymized studio totals + MRR for Support and Transparency pages.';
comment on function get_public_recent_donations is
  'Last N studio payments: amount_cents, created_at, is_recurring only (no PII).';
