-- First-party site traffic for the staff Moderator Dashboard (Traffic tab).
-- Operational measurement only. Not a public counter. Not advertising tracking.
-- Do not store raw IP addresses. Do not import third-party analytics.
-- Presence ids are anonymous and short-lived. No cross-day identity graph.
-- Safe to re-run.
--
-- Staging check:
--   1. Apply this file on the STAGING project (not production).
--   2. Open the staging site in one tab and browse a few pages.
--   3. Sign in as staff → Moderator Dashboard → Traffic (another tab).
--   4. Active now should be >= 1. The Traffic tab itself is not counted.
--   5. Range 1 hour / 7 days should show pageviews and a zero-safe chart.

create table if not exists public.traffic_presence (
  visitor_key text primary key,
  session_key text not null,
  user_id uuid,
  last_seen_at timestamptz not null default now(),
  path text not null default '/',
  signed_in boolean not null default false
);

comment on table public.traffic_presence is
  'Short-lived first-party presence. user_id is only for collapsing signed-in tabs; never expose in the Traffic UI.';

create index if not exists idx_traffic_presence_seen
  on public.traffic_presence (last_seen_at desc);

create table if not exists public.traffic_pageviews (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  session_key text not null,
  signed_in boolean not null default false,
  path text not null
);

comment on table public.traffic_pageviews is
  'First-party pageviews. session_key is anonymous; no IP, no user id.';

create index if not exists idx_traffic_pageviews_at
  on public.traffic_pageviews (occurred_at desc);

create index if not exists idx_traffic_pageviews_path_at
  on public.traffic_pageviews (path, occurred_at desc);

create table if not exists public.traffic_concurrent_samples (
  sampled_at timestamptz primary key,
  active_count integer not null default 0 check (active_count >= 0),
  signed_in_count integer not null default 0 check (signed_in_count >= 0),
  guest_count integer not null default 0 check (guest_count >= 0)
);

comment on table public.traffic_concurrent_samples is
  'Per-minute peak concurrent visitors for the staff Traffic chart.';

alter table public.traffic_presence enable row level security;
alter table public.traffic_pageviews enable row level security;
alter table public.traffic_concurrent_samples enable row level security;

revoke all on public.traffic_presence from public, anon, authenticated;
revoke all on public.traffic_pageviews from public, anon, authenticated;
revoke all on public.traffic_concurrent_samples from public, anon, authenticated;

grant all on public.traffic_presence to postgres, service_role;
grant all on public.traffic_pageviews to postgres, service_role;
grant all on public.traffic_concurrent_samples to postgres, service_role;

do $$
begin
  if to_regclass('public.traffic_pageviews_id_seq') is not null then
    execute 'grant usage, select on sequence public.traffic_pageviews_id_seq to postgres, service_role';
  end if;
end $$;

create or replace function public.sanitize_traffic_path(p_path text)
returns text
language plpgsql
immutable
as $$
declare
  v text;
begin
  v := split_part(split_part(coalesce(p_path, ''), '#', 1), '?', 1);
  v := trim(v);
  if v is null or v = '' then
    return '/';
  end if;
  if left(v, 1) <> '/' then
    v := '/' || v;
  end if;
  v := regexp_replace(v, '/{2,}', '/', 'g');
  if length(v) > 1 then
    v := regexp_replace(v, '/+$', '');
  end if;
  v := left(v, 200);
  if v ~* '^/(javascript|data|file|https?):' then
    return '/';
  end if;
  v := regexp_replace(v, '[^a-zA-Z0-9._~/%:@+\-]', '', 'g');
  if v is null or v = '' or left(v, 1) <> '/' then
    return '/';
  end if;
  return v;
end;
$$;

-- Collapse unbounded content URLs so the Pages list stays finite.
create or replace function public.traffic_page_bucket(p_path text)
returns text
language plpgsql
immutable
as $$
declare
  v text;
begin
  v := public.sanitize_traffic_path(p_path);
  if v ~ '^/ideas/[^/]+/edit$' then
    return '/ideas/:id/edit';
  end if;
  if v ~ '^/ideas/[^/]+$' and v not in ('/ideas/submit', '/ideas/wizard') then
    return '/ideas/:id';
  end if;
  if v ~ '^/u/[^/]+$' then
    return '/u/:username';
  end if;
  if v ~ '^/profile/[^/]+$' and v <> '/profile/edit' then
    return '/profile/:username';
  end if;
  if v ~ '^/released/[^/]+$' then
    return '/released/:slug';
  end if;
  if v ~ '^/projects/[^/]+/board(/staging)?$' then
    return '/projects/:id/board';
  end if;
  if v ~ '^/projects/[^/]+/contributors$' then
    return '/projects/:id/contributors';
  end if;
  return v;
end;
$$;

create or replace function public.record_traffic_heartbeat(
  p_session_key text,
  p_path text,
  p_is_pageview boolean default false
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session text;
  v_path text;
  v_uid uuid;
  v_visitor text;
  v_signed boolean;
  v_now timestamptz := now();
  v_minute timestamptz;
  v_active int := 0;
  v_signed_n int := 0;
  v_guest_n int := 0;
  v_prev_path text;
  v_prev_seen timestamptz;
begin
  v_session := trim(coalesce(p_session_key, ''));
  if v_session !~ '^[A-Za-z0-9_-]{16,64}$' then
    return json_build_object('ok', false);
  end if;

  v_path := public.sanitize_traffic_path(p_path);
  v_uid := auth.uid();
  v_signed := v_uid is not null;
  if v_signed then
    v_visitor := 'u:' || v_uid::text;
  else
    v_visitor := 's:' || v_session;
  end if;

  select path, last_seen_at
    into v_prev_path, v_prev_seen
  from public.traffic_presence
  where visitor_key = v_visitor;

  insert into public.traffic_presence (
    visitor_key, session_key, user_id, last_seen_at, path, signed_in
  ) values (
    v_visitor, v_session, v_uid, v_now, v_path, v_signed
  )
  on conflict (visitor_key) do update set
    session_key = excluded.session_key,
    user_id = excluded.user_id,
    last_seen_at = excluded.last_seen_at,
    path = excluded.path,
    signed_in = excluded.signed_in;

  delete from public.traffic_presence
  where last_seen_at < v_now - interval '5 minutes';

  select
    count(*)::int,
    count(*) filter (where signed_in)::int,
    count(*) filter (where not signed_in)::int
  into v_active, v_signed_n, v_guest_n
  from public.traffic_presence
  where last_seen_at > v_now - interval '60 seconds';

  v_minute := date_trunc('minute', v_now);
  insert into public.traffic_concurrent_samples (
    sampled_at, active_count, signed_in_count, guest_count
  ) values (
    v_minute, v_active, v_signed_n, v_guest_n
  )
  on conflict (sampled_at) do update set
    active_count = greatest(
      public.traffic_concurrent_samples.active_count,
      excluded.active_count
    ),
    signed_in_count = greatest(
      public.traffic_concurrent_samples.signed_in_count,
      excluded.signed_in_count
    ),
    guest_count = greatest(
      public.traffic_concurrent_samples.guest_count,
      excluded.guest_count
    );

  if coalesce(p_is_pageview, false)
     and (
       v_prev_path is null
       or v_prev_path is distinct from v_path
       or v_prev_seen is null
       or v_prev_seen < v_now - interval '2 seconds'
     )
  then
    insert into public.traffic_pageviews (
      occurred_at, session_key, signed_in, path
    ) values (
      v_now, v_session, v_signed, v_path
    );
  end if;

  return json_build_object('ok', true);
end;
$$;

create or replace function public.get_traffic_active_now()
returns json
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_active int := 0;
  v_signed int := 0;
  v_guest int := 0;
begin
  if not public.is_staff() then
    raise exception 'STAFF_ONLY' using errcode = '42501';
  end if;

  select
    count(*)::int,
    count(*) filter (where signed_in)::int,
    count(*) filter (where not signed_in)::int
  into v_active, v_signed, v_guest
  from public.traffic_presence
  where last_seen_at > now() - interval '60 seconds';

  return json_build_object(
    'active_now', v_active,
    'signed_in', v_signed,
    'guests', v_guest
  );
end;
$$;

create or replace function public.get_traffic_report(p_range text default '7d')
returns json
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_range text;
  v_to timestamptz := now();
  v_from timestamptz;
  v_step interval;
  v_bucket text;
  v_pv_min timestamptz;
  v_sample_min timestamptz;
begin
  if not public.is_staff() then
    raise exception 'STAFF_ONLY' using errcode = '42501';
  end if;

  v_range := lower(trim(coalesce(p_range, '7d')));

  case v_range
    when '1h' then
      v_from := v_to - interval '1 hour';
      v_step := interval '1 minute';
      v_bucket := '1 minute';
    when '6h' then
      v_from := v_to - interval '6 hours';
      v_step := interval '5 minutes';
      v_bucket := '5 minutes';
    when '12h' then
      v_from := v_to - interval '12 hours';
      v_step := interval '10 minutes';
      v_bucket := '10 minutes';
    when '24h' then
      v_from := v_to - interval '24 hours';
      v_step := interval '15 minutes';
      v_bucket := '15 minutes';
    when '3d' then
      v_from := v_to - interval '3 days';
      v_step := interval '1 hour';
      v_bucket := '1 hour';
    when '7d' then
      v_from := v_to - interval '7 days';
      v_step := interval '1 hour';
      v_bucket := '1 hour';
    when '14d' then
      v_from := v_to - interval '14 days';
      v_step := interval '2 hours';
      v_bucket := '2 hours';
    when '21d' then
      v_from := v_to - interval '21 days';
      v_step := interval '3 hours';
      v_bucket := '3 hours';
    when '30d' then
      v_from := v_to - interval '30 days';
      v_step := interval '6 hours';
      v_bucket := '6 hours';
    when '3m' then
      v_from := v_to - interval '3 months';
      v_step := interval '1 day';
      v_bucket := '1 day';
    when '6m' then
      v_from := v_to - interval '6 months';
      v_step := interval '1 day';
      v_bucket := '1 day';
    when '9m' then
      v_from := v_to - interval '9 months';
      v_step := interval '1 day';
      v_bucket := '1 day';
    when '12m' then
      v_from := v_to - interval '12 months';
      v_step := interval '7 days';
      v_bucket := '1 week';
    when '3y' then
      v_from := v_to - interval '3 years';
      v_step := interval '7 days';
      v_bucket := '1 week';
    when 'lifetime' then
      select min(occurred_at) into v_pv_min from public.traffic_pageviews;
      select min(sampled_at) into v_sample_min from public.traffic_concurrent_samples;
      v_from := least(
        coalesce(v_pv_min, v_to),
        coalesce(v_sample_min, v_to)
      );
      if v_from >= v_to - interval '1 day' then
        v_from := v_to - interval '1 day';
      end if;
      -- date_bin cannot use month/year strides
      v_step := interval '7 days';
      v_bucket := '1 week';
    else
      v_range := '7d';
      v_from := v_to - interval '7 days';
      v_step := interval '1 hour';
      v_bucket := '1 hour';
  end case;

  return (
    with buckets as (
      select generate_series(v_from, v_to, v_step) as t
    ),
    pv as (
      select
        date_bin(v_step, occurred_at, v_from) as t,
        count(*)::int as pageviews
      from public.traffic_pageviews
      where occurred_at >= v_from
        and occurred_at <= v_to
      group by 1
    ),
    cc as (
      select
        date_bin(v_step, sampled_at, v_from) as t,
        max(active_count)::int as concurrent
      from public.traffic_concurrent_samples
      where sampled_at >= v_from
        and sampled_at <= v_to
      group by 1
    ),
    series as (
      select
        b.t,
        coalesce(cc.concurrent, 0) as concurrent,
        coalesce(pv.pageviews, 0) as pageviews
      from buckets b
      left join pv on pv.t = b.t
      left join cc on cc.t = b.t
      order by b.t
    ),
    totals as (
      select
        count(*)::int as pageviews,
        count(distinct session_key)::int as unique_visitors,
        count(distinct session_key) filter (where signed_in)::int
          as signed_in_visitors,
        count(distinct session_key) filter (where not signed_in)::int
          as guest_visitors,
        count(*) filter (where signed_in)::int as signed_in_pageviews,
        count(*) filter (where not signed_in)::int as guest_pageviews
      from public.traffic_pageviews
      where occurred_at >= v_from
        and occurred_at <= v_to
    ),
    top_pages as (
      select
        public.traffic_page_bucket(path) as path,
        count(*)::int as pageviews,
        count(distinct path)::int as unique_pages
      from public.traffic_pageviews
      where occurred_at >= v_from
        and occurred_at <= v_to
      group by 1
      order by pageviews desc, path asc
    ),
    live as (
      select
        count(*)::int as active_now,
        count(*) filter (where signed_in)::int as signed_in,
        count(*) filter (where not signed_in)::int as guests
      from public.traffic_presence
      where last_seen_at > now() - interval '60 seconds'
    )
    select json_build_object(
      'range', v_range,
      'bucket', v_bucket,
      'from', v_from,
      'to', v_to,
      'active_now', (select active_now from live),
      'unique_visitors', coalesce((select unique_visitors from totals), 0),
      'pageviews', coalesce((select pageviews from totals), 0),
      'signed_in_visitors', coalesce((select signed_in_visitors from totals), 0),
      'guest_visitors', coalesce((select guest_visitors from totals), 0),
      'signed_in_pageviews', coalesce((select signed_in_pageviews from totals), 0),
      'guest_pageviews', coalesce((select guest_pageviews from totals), 0),
      'series', coalesce(
        (
          select json_agg(
            json_build_object(
              't', s.t,
              'concurrent', s.concurrent,
              'pageviews', s.pageviews
            )
            order by s.t
          )
          from series s
        ),
        '[]'::json
      ),
      'top_pages', coalesce(
        (
          select json_agg(
            json_build_object(
              'path', tp.path,
              'pageviews', tp.pageviews,
              'unique_pages', tp.unique_pages
            )
            order by tp.pageviews desc, tp.path asc
          )
          from top_pages tp
        ),
        '[]'::json
      )
    )
  );
end;
$$;

revoke all on function public.sanitize_traffic_path(text) from public;
revoke all on function public.traffic_page_bucket(text) from public;
revoke all on function public.record_traffic_heartbeat(text, text, boolean) from public;
revoke all on function public.get_traffic_active_now() from public;
revoke all on function public.get_traffic_report(text) from public;

grant execute on function public.sanitize_traffic_path(text)
  to anon, authenticated, service_role;
grant execute on function public.traffic_page_bucket(text)
  to authenticated, service_role;
grant execute on function public.record_traffic_heartbeat(text, text, boolean)
  to anon, authenticated, service_role;
grant execute on function public.get_traffic_active_now()
  to authenticated, service_role;
grant execute on function public.get_traffic_report(text)
  to authenticated, service_role;

notify pgrst, 'reload schema';
